# Random values generated by Terraform for infra-level credentials.
# cs/<env>/jwt is deliberately NOT generated here — a signing key nobody's
# tracked the rotation of is worse than an empty secret waiting for a real
# one (spec: docs/superpowers/specs/2026-08-02-backend-phase2-design.md).

resource "random_password" "db_master" {
  length  = 32
  special = false # Aurora master password disallows some special characters
}

resource "aws_secretsmanager_secret" "db_master" {
  name = "cs/${var.environment}/db/master"
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id     = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({ username = "dbadmin", password = random_password.db_master.result })
}

resource "random_password" "db_app" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "db_app" {
  name = "cs/${var.environment}/db/app"
}

resource "aws_secretsmanager_secret_version" "db_app" {
  secret_id     = aws_secretsmanager_secret.db_app.id
  secret_string = jsonencode({ username = "cs_app", password = random_password.db_app.result })
}

resource "random_password" "redis_auth" {
  length  = 32
  special = false # Redis AUTH tokens disallow some special characters too
}

resource "aws_secretsmanager_secret" "redis_auth" {
  name = "cs/${var.environment}/redis/auth"
}

resource "aws_secretsmanager_secret_version" "redis_auth" {
  secret_id     = aws_secretsmanager_secret.redis_auth.id
  secret_string = random_password.redis_auth.result
}

resource "random_password" "alb_origin_verify" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "alb_origin_verify" {
  name = "cs/${var.environment}/alb/origin-verify"
}

resource "aws_secretsmanager_secret_version" "alb_origin_verify" {
  secret_id     = aws_secretsmanager_secret.alb_origin_verify.id
  secret_string = random_password.alb_origin_verify.result
}

# Empty on purpose — fill in manually once the backend app exists and a
# real signing key is generated and tracked. Currently unused: curryspacebe's
# env schema (src/config/env.ts) has no JWT_SIGNING_KEY field, so this isn't
# wired into any task's injected secrets yet.
#
# Superseded by jwt_access_secret/jwt_refresh_secret below (spec 0006 landed
# two separate JWT secrets, not one) — this one stays as-is, still unused,
# rather than repurposing an already-applied resource sight-unseen. Fine to
# remove in a follow-up cleanup.
resource "aws_secretsmanager_secret" "jwt" {
  name = "cs/${var.environment}/jwt"
}

resource "random_password" "cookie_secret" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "cookie_secret" {
  name = "cs/${var.environment}/cookie-secret"
}

resource "aws_secretsmanager_secret_version" "cookie_secret" {
  secret_id     = aws_secretsmanager_secret.cookie_secret.id
  secret_string = random_password.cookie_secret.result
}

# curryspacebe's env schema (src/config/env.ts) reads DATABASE_URL/REDIS_URL
# as single connection strings, not a host + a separate credentials secret —
# so the values assembled here, not db_app/redis_auth directly, are what's
# injected into the containers (compute.tf). db_app/redis_auth remain as-is
# since aws_db_proxy.this's SECRETS auth scheme (database.tf) requires that
# exact username/password JSON shape.
#
# Target database is "postgres" -- the guaranteed default Aurora PostgreSQL
# database, since no application database/role has been created yet (that's
# a migration/bootstrap step, still deferred per this task's brief).
resource "aws_secretsmanager_secret" "database_url" {
  name = "cs/${var.environment}/database-url"
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = "postgresql://cs_app:${random_password.db_app.result}@${aws_db_proxy.this.endpoint}:5432/postgres"
}

resource "aws_secretsmanager_secret" "redis_url" {
  name = "cs/${var.environment}/redis-url"
}

resource "aws_secretsmanager_secret_version" "redis_url" {
  secret_id = aws_secretsmanager_secret.redis_url.id
  # rediss:// (double s), not redis:// -- redis.tf sets
  # transit_encryption_enabled = true, so the replication group only accepts
  # TLS connections; ioredis switches into TLS mode based on this scheme.
  secret_string = "rediss://:${random_password.redis_auth.result}@${aws_elasticache_replication_group.this.primary_endpoint_address}:6379"
}

# --- Auth & identity (spec 0006) ---

resource "random_password" "jwt_access_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "jwt_access_secret" {
  name = "cs/${var.environment}/jwt-access-secret"
}

resource "aws_secretsmanager_secret_version" "jwt_access_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_access_secret.id
  secret_string = random_password.jwt_access_secret.result
}

resource "random_password" "jwt_refresh_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "jwt_refresh_secret" {
  name = "cs/${var.environment}/jwt-refresh-secret"
}

resource "aws_secretsmanager_secret_version" "jwt_refresh_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_refresh_secret.id
  secret_string = random_password.jwt_refresh_secret.result
}

resource "random_password" "guest_token_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "guest_token_secret" {
  name = "cs/${var.environment}/guest-token-secret"
}

resource "aws_secretsmanager_secret_version" "guest_token_secret" {
  secret_id     = aws_secretsmanager_secret.guest_token_secret.id
  secret_string = random_password.guest_token_secret.result
}

# Empty on purpose, same reasoning as the jwt placeholder above — this is an
# asymmetric keypair (RS256), not a random string, so Terraform can't
# generate the value here and have it mean anything on the other side: the
# private half lives here, but the *public* half has to reach currystudiobe
# (a separate repo, deployed to a plain EC2 .env, not Secrets Manager) for
# the two to verify against each other. Fill this in via
# `aws secretsmanager put-secret-value` right after apply — see the PR
# description for the exact command and the matching public key.
resource "aws_secretsmanager_secret" "space_handoff_private_key" {
  name = "cs/${var.environment}/space-handoff-private-key"
}

# Cursor pagination (spec 0004) — env.ts's CURSOR_SIGNING_SECRET was never
# wired into infra when 0004 shipped, so a container running an image built
# after that landed crash-loops on boot (missing required env var) even
# though nothing about this secret changed. Same random_password pattern as
# cookie_secret; no cross-repo counterpart needed since this only signs/
# verifies cursors within curryspacebe itself.
resource "random_password" "cursor_signing_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "cursor_signing_secret" {
  name = "cs/${var.environment}/cursor-signing-secret"
}

resource "aws_secretsmanager_secret_version" "cursor_signing_secret" {
  secret_id     = aws_secretsmanager_secret.cursor_signing_secret.id
  secret_string = random_password.cursor_signing_secret.result
}

# Search (spec 0016) — Meilisearch master key. Used two ways: injected into
# the self-hosted Meilisearch task itself (meilisearch.tf) to set/enforce it
# as that server's own master key, and into api/worker/scheduler (compute.tf)
# where env.ts's MEILI_MASTER_KEY is optional-on-purpose (0016 final review) —
# each process derives its one scoped key from this at boot and never uses it
# at request/job time. Same random_password pattern as the other signing
# secrets; no cross-repo counterpart needed.
resource "random_password" "meili_master_key" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "meili_master_key" {
  name = "cs/${var.environment}/meili-master-key"
}

resource "aws_secretsmanager_secret_version" "meili_master_key" {
  secret_id     = aws_secretsmanager_secret.meili_master_key.id
  secret_string = random_password.meili_master_key.result
}
