# Random values generated by Terraform for infra-level credentials.
# cs/<env>/jwt is deliberately NOT generated here — a signing key nobody's
# tracked the rotation of is worse than an empty secret waiting for a real
# one (spec: docs/superpowers/specs/2026-08-02-backend-phase2-design.md).

resource "random_password" "db_master" {
  length  = 32
  special = false # Aurora master password disallows some special characters
}

resource "aws_secretsmanager_secret" "db_master" {
  name = "cs/${var.environment}/db/master"
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id     = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({ username = "dbadmin", password = random_password.db_master.result })
}

resource "random_password" "db_app" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "db_app" {
  name = "cs/${var.environment}/db/app"
}

resource "aws_secretsmanager_secret_version" "db_app" {
  secret_id     = aws_secretsmanager_secret.db_app.id
  secret_string = jsonencode({ username = "cs_app", password = random_password.db_app.result })
}

resource "random_password" "redis_auth" {
  length  = 32
  special = false # Redis AUTH tokens disallow some special characters too
}

resource "aws_secretsmanager_secret" "redis_auth" {
  name = "cs/${var.environment}/redis/auth"
}

resource "aws_secretsmanager_secret_version" "redis_auth" {
  secret_id     = aws_secretsmanager_secret.redis_auth.id
  secret_string = random_password.redis_auth.result
}

resource "random_password" "alb_origin_verify" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "alb_origin_verify" {
  name = "cs/${var.environment}/alb/origin-verify"
}

resource "aws_secretsmanager_secret_version" "alb_origin_verify" {
  secret_id     = aws_secretsmanager_secret.alb_origin_verify.id
  secret_string = random_password.alb_origin_verify.result
}

# Empty on purpose — fill in manually once the backend app exists and a
# real signing key is generated and tracked.
resource "aws_secretsmanager_secret" "jwt" {
  name = "cs/${var.environment}/jwt"
}
