# Random values generated by Terraform for infra-level credentials.
# cs/<env>/jwt is deliberately NOT generated here — a signing key nobody's
# tracked the rotation of is worse than an empty secret waiting for a real
# one (spec: docs/superpowers/specs/2026-08-02-backend-phase2-design.md).

resource "random_password" "db_master" {
  length  = 32
  special = false # Aurora master password disallows some special characters
}

resource "aws_secretsmanager_secret" "db_master" {
  name = "cs/${var.environment}/db/master"
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id     = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({ username = "dbadmin", password = random_password.db_master.result })
}

resource "random_password" "db_app" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "db_app" {
  name = "cs/${var.environment}/db/app"
}

resource "aws_secretsmanager_secret_version" "db_app" {
  secret_id     = aws_secretsmanager_secret.db_app.id
  secret_string = jsonencode({ username = "cs_app", password = random_password.db_app.result })
}

resource "random_password" "redis_auth" {
  length  = 32
  special = false # Redis AUTH tokens disallow some special characters too
}

resource "aws_secretsmanager_secret" "redis_auth" {
  name = "cs/${var.environment}/redis/auth"
}

resource "aws_secretsmanager_secret_version" "redis_auth" {
  secret_id     = aws_secretsmanager_secret.redis_auth.id
  secret_string = random_password.redis_auth.result
}

resource "random_password" "alb_origin_verify" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "alb_origin_verify" {
  name = "cs/${var.environment}/alb/origin-verify"
}

resource "aws_secretsmanager_secret_version" "alb_origin_verify" {
  secret_id     = aws_secretsmanager_secret.alb_origin_verify.id
  secret_string = random_password.alb_origin_verify.result
}

# Empty on purpose — fill in manually once the backend app exists and a
# real signing key is generated and tracked. Currently unused: curryspacebe's
# env schema (src/config/env.ts) has no JWT_SIGNING_KEY field, so this isn't
# wired into any task's injected secrets yet.
resource "aws_secretsmanager_secret" "jwt" {
  name = "cs/${var.environment}/jwt"
}

resource "random_password" "cookie_secret" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "cookie_secret" {
  name = "cs/${var.environment}/cookie-secret"
}

resource "aws_secretsmanager_secret_version" "cookie_secret" {
  secret_id     = aws_secretsmanager_secret.cookie_secret.id
  secret_string = random_password.cookie_secret.result
}

# curryspacebe's env schema (src/config/env.ts) reads DATABASE_URL/REDIS_URL
# as single connection strings, not a host + a separate credentials secret —
# so the values assembled here, not db_app/redis_auth directly, are what's
# injected into the containers (compute.tf). db_app/redis_auth remain as-is
# since aws_db_proxy.this's SECRETS auth scheme (database.tf) requires that
# exact username/password JSON shape.
#
# Target database is "postgres" -- the guaranteed default Aurora PostgreSQL
# database, since no application database/role has been created yet (that's
# a migration/bootstrap step, still deferred per this task's brief).
resource "aws_secretsmanager_secret" "database_url" {
  name = "cs/${var.environment}/database-url"
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = "postgresql://cs_app:${random_password.db_app.result}@${aws_db_proxy.this.endpoint}:5432/postgres"
}

resource "aws_secretsmanager_secret" "redis_url" {
  name = "cs/${var.environment}/redis-url"
}

resource "aws_secretsmanager_secret_version" "redis_url" {
  secret_id = aws_secretsmanager_secret.redis_url.id
  # rediss:// (double s), not redis:// -- redis.tf sets
  # transit_encryption_enabled = true, so the replication group only accepts
  # TLS connections; ioredis switches into TLS mode based on this scheme.
  secret_string = "rediss://:${random_password.redis_auth.result}@${aws_elasticache_replication_group.this.primary_endpoint_address}:6379"
}
